
version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=your_api_key_here
      - LLM_URL=http://llama_cpp:5000/completion
    depends_on:
      - llama_cpp

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  llama_cpp:
    image: ghcr.io/ggerganov/llama.cpp:${LLAMA_MODE}
    runtime: ${GPU_RUNTIME}
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_DEVICES}
    volumes:
      - ./models:/models
    ports:
      - "5000:5000"
    command: [ "--model", "/models/your_model.gguf", "--port", "5000" ]
